# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2018-07-31 18:11
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='student_feedback',
            fields=[
                ('auto_increment_id', models.AutoField(primary_key=True, serialize=False)),
                ('student_id', models.IntegerField()),
                ('username', models.CharField(default=0, max_length=40)),
                ('course_id', models.IntegerField(default=0)),
                ('course', models.CharField(default=0, max_length=40)),
                ('datetime', models.DateTimeField(blank=True, null=True)),
                ('rating', models.IntegerField(default=0)),
                ('comment', models.CharField(blank=True, max_length=200)),
            ],
            options={
                'db_table': 'classcast_student_feedback',
            },
        ),
    ]
